services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - ./.env
  redis:
    image: redis
    expose:
      - 6379
  web:
    build: .
    command: >
      /bin/bash -c 'python manage.py wait_for_db &&
                    python manage.py migrate --noinput &&
                    python manage.py makemigrations --noinput &&
                    python manage.py migrate --noinput &&
                    python manage.py collectstatic --noinput &&
                    daphne -b 0.0.0.0 -p 8000 blogpost.asgi:application'
    volumes:
      - static_data:/app/blogpost-project/static
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  celery:
    restart: always
    build: .
    command: >
      /bin/bash -c 'celery -A blogpost worker -l info &&
                    celery -A blogpost beat -l info'
    volumes:
      - celery_data:/app/blogpost-project
    env_file:
      - ./.env
    depends_on:
      - redis
      - web
  nginx:
    image: nginx
    restart: always
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/blogpost-project/static
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  postgres_data:
  static_data:
  celery_data:
