services:
  db:
    restart: on-failure:5
    image: postgres:14.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
  redis:
    restart: on-failure:5
    image: redis:7.0.5
  web:
    restart: on-failure:5
    build: .
    command: >
      /bin/bash -c 'python manage.py wait_for_db &&
                    python manage.py makemigrations --noinput &&
                    python manage.py migrate --noinput &&
                    python manage.py collectstatic --noinput &&
                    gunicorn -b 0.0.0.0:8000 -w 3 blogpost.wsgi:application'
    volumes:
      - workdir:/app/blogpost-project/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  channels:
    restart: on-failure:5
    build: .
    command: >
      /bin/bash -c 'daphne -b 0.0.0.0 -p 8001 blogpost.asgi:application'
    expose:
      - 8001
    env_file:
      - ./.env
    volumes:
      - workdir:/app/blogpost-project/
    depends_on:
      - web
  celery:
    restart: on-failure:5
    build: .
    command: >
      /bin/bash -c 'celery -A blogpost worker -l info &&
                    celery -A blogpost beat -l info'
    volumes:
      - workdir:/app/blogpost-project
    env_file:
      - ./.env
    depends_on:
      - web
  nginx:
    image: nginx
    restart: on-failure:5
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - workdir:/app/blogpost-project/
    ports:
      - "80:80"
    depends_on:
      - channels
volumes:
  postgres_data:
  workdir:
