# Generated by Django 4.0.6 on 2022-11-07 13:20

import diary.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_customuser_last_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[diary.validators.profanity]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, validators=[diary.validators.profanity]),
        ),
    ]
