"""
Django settings for postways project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from root .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================================
# ENVIRONMENT VARIABLES CONFIGURATION
# ============================================================================
# 
# This section documents ALL environment variables used by the application.
# All variables are loaded from the root .env file via load_dotenv() above.
#
# REQUIRED VARIABLES (must be in .env):
#   - SECRET_KEY: Django secret key (CRITICAL - never commit to git)
#   - DATABASE_PASSWORD: Database password
#   - EMAIL_HOST_PASSWORD: SMTP email password
#
# OPTIONAL VARIABLES (have defaults, can override in .env):
#   - DATABASE_HOST: Database host (default: 'localhost', Docker: 'db')
#   - DATABASE_PORT: Database port (default: '5432')
#   - DATABASE_NAME: Database name (default: 'blogpost_db')
#   - DATABASE_USER: Database user (default: 'blogpost_user')
#   - REDIS_HOST: Redis host (default: 'localhost', Docker: 'redis')
#   - REDIS_PORT: Redis port (default: 6379)
#   - WEEKLY_REPORT_RECIPIENTS: Comma-separated email list (default: 'ruslanways@gmail.com')
#
# NOTE: For local development, local_settings.py can override DATABASE_* variables
# with different defaults (e.g., DATABASE_NAME=postgres, DATABASE_USER=postgres)
#
# WHERE SETTINGS ARE DEFINED:
#   1. Hardcoded in settings.py: Application structure, Django config, static/media paths
#   2. Environment variables (.env): Secrets, passwords, environment-specific values
#   3. local_settings.py: Local development overrides (DEBUG=True, local DB config)
#      - Only loaded when NOT in Docker/production
#      - Can use env vars or hardcoded values for local convenience
#
# ============================================================================

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', ' ')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['postways.net', 'www.postways.net', 'localhost', 'localhost:8001', '3.73.45.193']

APPEND_SLASH = True

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# ============================================================================
# ENVIRONMENT VARIABLES - Load all env vars in one place
# ============================================================================

# Database configuration (DATABASE_* prefix for consistency)
DATABASE_HOST = os.environ.get('DATABASE_HOST', 'localhost')
DATABASE_PORT = os.environ.get('DATABASE_PORT', '5432')
DATABASE_NAME = os.environ.get('DATABASE_NAME', 'blogpost_db')
DATABASE_USER = os.environ.get('DATABASE_USER', 'blogpost_user')
DATABASE_PASSWORD = os.environ.get('DATABASE_PASSWORD')

# Redis configuration (used for both Channels and Celery)
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.environ.get('REDIS_PORT', 6379))

# Email configuration
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

# Weekly report recipients
WEEKLY_REPORT_RECIPIENTS = os.environ.get('WEEKLY_REPORT_RECIPIENTS', 'ruslanways@gmail.com').split(',')

# ============================================================================
# CHANNEL LAYERS (Django Channels - WebSocket support)
# ============================================================================

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

# Application definition
INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'diary.apps.DiaryConfig',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_spectacular',
]

AUTH_USER_MODEL = 'diary.CustomUser'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'diary.middleware.UserLastRequestMiddleware',
    'diary.middleware.UncaughtExceptionMiddleware',
]

INTERNAL_IPS = [
    '127.0.0.1',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================
# Production database settings (can be overridden by local_settings.py)
# In Docker: DATABASE_HOST should be 'db', REDIS_HOST should be 'redis'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USER,
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': DATABASE_HOST,
        'PORT': DATABASE_PORT,
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Ensure log directory exists before configuring logging
LOG_DIR = BASE_DIR / 'var' / 'logs'
LOG_DIR.mkdir(parents=True, exist_ok=True)

# Ensure celery directory exists for runtime artifacts
CELERY_DIR = BASE_DIR / 'var' / 'celery'
CELERY_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'other_errors': {
            'format': '{levelname} - {asctime} - {module} - {process: d} - {thread: d} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': LOG_DIR / 'other_errors.log',
            'formatter': 'other_errors',
        },
    },
    'loggers': {
        'diary.middleware': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# EMAIL CONFIGURATION
# ============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'ruslanways@gmail.com'
DEFAULT_FROM_EMAIL = 'Postways Social Network <ruslanways@gmail.com>'
# EMAIL_HOST_PASSWORD loaded from env vars above

# ============================================================================
# CELERY CONFIGURATION
# ============================================================================
# Uses REDIS_HOST and REDIS_PORT loaded from env vars above
CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/1"
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/1"

# Store celerybeat schedule database in var/celery directory
CELERY_BEAT_SCHEDULE_FILENAME = str(CELERY_DIR / 'celerybeat-schedule')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication'
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('JWT',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Postways OpenApi 3.0.3 documentation',
    'DESCRIPTION': 'It is a simple web-application with interest posts and likes functionality.',
    'CONTACT': {'email': 'ruslanways@gmail.com'},
    'LICENSE': {'name': 'MIT License'},
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api/v1/',
    'COMPONENT_SPLIT_REQUEST': True,
    'AUTHENTICATION_WHITELIST': ['rest_framework_simplejwt.authentication.JWTAuthentication'],
    'TAGS': [
        {'name': 'default', 'description': 'Root of all api'},
        {'name': 'auth', 'description': 'All authorization system enpoints'},
        {'name': 'likes', 'description': 'Operations with likes'},
        {'name': 'posts', 'description': 'Posts enpoints'},
        {'name': 'users', 'description': 'Users enpoints'},
    ],
}

# WEEKLY_REPORT_RECIPIENTS loaded from env vars above

# ============================================================================
# LOCAL SETTINGS OVERRIDE
# ============================================================================
# Load local_settings.py if it exists (for local development only)
# This file is NOT used in Docker or production environments
# See local_settings.py for what it overrides
try:
    from .local_settings import *
except ImportError:
    print("Production settings apply")

