# Generated by Django 4.0.6 on 2023-06-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='diary/images/thumbnails/'),
        ),
    ]
