# Generated by Django 4.0.6 on 2023-06-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
