# Generated by Django 4.0.6 on 2023-06-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='diary/images/thumbnails/'),
        ),
    ]
