# Generated by Django 4.0.6 on 2023-07-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, max_length=200, null=True, upload_to='diary/images/thumbnails/'),
        ),
    ]
