# Generated by Django 4.0.6 on 2022-09-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_request',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last request'),
        ),
    ]
